#!/bin/bash
# WebOS Ad Removal
# WARNING! This script is provided with no warranty, use at your own risk. 
set -e

############ Begin User Customizable ENV Variables
# Set WAR_ENABLED=false to disable this script.
WAR_ENABLED=true
TOP_SHELF_ENABLED=true
AI_BOARD_ENABLED=true
RECOMMENDED_ENABLED=true
############ END User Customizable ENV Variables. Advanced users only past this point.

# This is the directory we will mount override files from.
WORKDIR="/tmp/webos_ad_removal"

# These are the source files that we will copy and modify.
AI_BOARD_SOURCE="/usr/palm/applications/com.webos.app.home/qml/UserInterfaceLayer/Containers/Main/AIBoard.qml"
RECOMMENDED_SOURCE="/usr/palm/applications/com.webos.app.home/qml/UserInterfaceLayer/Containers/Main/Recommended.qml"
TOP_SHELF_SOURCE="/usr/palm/applications/com.webos.app.home/qml/UserInterfaceLayer/Containers/Main/TopShelf.qml"
APP_INTERFACES_SOURCE="/usr/palm/applications/com.webos.app.home/qml/Interfaces/AppInterfaces/AppInterfaces.qml"

check_war_enabled() {
    # This can be used to disable the script while keeping it in place. Set WAR_ENABLED to false in the env variables above.
    if [ $WAR_ENABLED = false ]; then
        echo "WAR_ENABLED set to false, exiting."
        rm -fr $WORKDIR
        exit 1
    fi
}

check_install() {
    # Check if installed. If not do install. If installed run from install location to ensure applying user settings
    if [ ! -f "/var/lib/webosbrew/init.d/webos_ad_remover" ]; then
        echo "Script is not installed. Installing."
        curl -s -L https://raw.githubusercontent.com/Janzzze/webos-remove-ads/main/webos_custom_home_screen > /var/lib/webosbrew/init.d/webos_ad_remover
        chmod +x /var/lib/webosbrew/init.d/webos_ad_remover
    else
    script_name1=`basename $0`
    script_path1=`dirname $0`
    script_path_with_name="$script_path1/$script_name1"
        if [ "$script_path_with_name" = "/var/lib/webosbrew/init.d/webos_ad_remover" ]; then
            echo "Script installed and started from right location, executing."
        else
            echo "Runnning Script from right location."
            (/var/lib/webosbrew/init.d/webos_ad_remover)
            exit 1
        fi
    fi
}

check_target_sums() {
    # We check sha512 sum of target files before proceeding. We will be inserting a line of code at a specific line, we do this to ensure
    # there are no unexpected results. Old versions of WebOS or updates may cause files to change, which will break this script.
    case $1 in
    "ai_board")
        AI_BOARD_SUM="a1c448041bbbe30ab0986b8653a08b666185aca50fc91200b98a9b79ddeb0a6f3baef7f811b0a9f71ddd9814dfd471c1612e7e12de68e84fc794a231a3b6f0e3  /usr/palm/applications/com.webos.app.home/qml/UserInterfaceLayer/Containers/Main/AIBoard.qml"
        AI_BOARD_CHECK=$(sha512sum $AI_BOARD_SOURCE)

        if [ "$AI_BOARD_SUM" != "$AI_BOARD_CHECK" ]; then
            echo "Shasum did not match for AIBoard.qml! Script will not proceed!"
            exit 1
        fi
            echo "Checksum matched!"
        ;;
    "recommended")
        RECOMMENDED_SUM="29644d32182e478e78ab972eaab4f895c0290d568f293a5b0f248259f01316f53472f769f9631fa8a958256c79d122ae52cf53a5437e60026d0414ab3647d3e0  /usr/palm/applications/com.webos.app.home/qml/UserInterfaceLayer/Containers/Main/Recommended.qml"
        RECOMMENDED_CHECK=$(sha512sum $RECOMMENDED_SOURCE)

        if [ "$RECOMMENDED_SUM" != "$RECOMMENDED_CHECK" ]; then
            echo "Shasum did not match for Recommended.qml! Script will not proceed!"
            exit 1
        fi
            echo "Checksum matched!"
        ;;
    "top_shelf")
        TOP_SHELF_SUM="d142a5625a63dd5913afe02c4e216a7b48106025db7b34d89db641a19b7b7e0170a66956c5400af3cc0aa35816a62cad1ce4d8fac8b33f01d49b2652a1461904  /usr/palm/applications/com.webos.app.home/qml/UserInterfaceLayer/Containers/Main/TopShelf.qml"
        TOP_SHELF_CHECK=$(sha512sum $TOP_SHELF_SOURCE)

        if [ "$TOP_SHELF_SUM" != "$TOP_SHELF_CHECK" ]; then
            echo "Shasum did not match for TopShelf.qml! Script will not proceed!"
            exit 1
        fi
            echo "Checksum matched!"
        ;;
    *)
        echo "Attempted to check sum with unrecognized argument! Exiting."
        exit 1
        ;;
    esac
}

check_workdir() {
    # Del workimg directory and recreate it every script run.
    if [ ! -d "$WORKDIR" ]; then
        mkdir -p $WORKDIR
    fi
}

create_ai_board_override() {
    #! mountpoint -q "$AI_BOARD_SOURCE" || umount "$AI_BOARD_SOURCE"
    umount "$AI_BOARD_SOURCE" > /dev/null 2>&1 || :
    check_target_sums "ai_board"
    # This runs if the modified file is not found.
    # Then we copy the AIBoard.qml file to our workdir.
    cp $AI_BOARD_SOURCE "$WORKDIR/AIBoard.qml"

    # Finally we modify the file.
    sed -i '17 i return' "$WORKDIR/AIBoard.qml"
}

remove_ai_board() {
    # First we check if the AIBoard.qml file exists on the USB. If it does not we create it.
    if [ $AI_BOARD_ENABLED = true ]; then
        if [ ! -f "$WORKDIR/AIBoard.qml" ]; then
            echo "AIBoard override file did not exist. Creating one now."
            create_ai_board_override
        else
            echo "AIBoard override file found at $WORKDIR/AIBoard.qml"
        fi
        # Then we mount --bind the AIBoard.qml override file. This is a non destructive action that can be reset with a reboot or umount.
        mount --bind "$WORKDIR/AIBoard.qml" "$AI_BOARD_SOURCE"
    else
        echo "AIBoard block disabled. Reverting changes"
        #! mountpoint -q "$AI_BOARD_SOURCE" || umount "$AI_BOARD_SOURCE"
        umount "$AI_BOARD_SOURCE" > /dev/null 2>&1 || :
        rm -fr $WORKDIR/AIBoard.qml
    fi
}

create_recommended_override() {
    #! mountpoint -q "$RECOMMENDED_SOURCE" || umount "$RECOMMENDED_SOURCE"
    umount "$RECOMMENDED_SOURCE" > /dev/null 2>&1 || :
    check_target_sums "recommended"
    # This runs if the modified file is not found.
    # Then we copy the Recommended.qml file to our workdir.
    cp $RECOMMENDED_SOURCE "$WORKDIR/Recommended.qml"

    # Finally we modify the file.
    sed -i '17 i return' "$WORKDIR/Recommended.qml"
}

remove_recommended() {
    # First we check if the Recommended.qml file exists on the USB.
    if [ $RECOMMENDED_ENABLED = true ]; then
        if [ ! -f "$WORKDIR/Recommended.qml" ]; then
            echo "Recommended override file did not exist. Creating one now."
            create_recommended_override
        else
            echo "Recommended override file found at $WORKDIR/Recommended.qml"
        fi
        # Then we mount --bind the Recommended.qml override file. This is a non destructive action that can be reset with a reboot or umount.
        mount --bind "$WORKDIR/Recommended.qml" "$RECOMMENDED_SOURCE"
    else
        echo "Recommended block disabled. Reverting changes"
        #! mountpoint -q "$RECOMMENDED_SOURCE" || umount "$RECOMMENDED_SOURCE"
        umount "$RECOMMENDED_SOURCE" > /dev/null 2>&1 || :
        rm -fr $WORKDIR/Recommended.qml
    fi
}

create_top_shelf_override() {
    umount "$TOP_SHELF_SOURCE" > /dev/null 2>&1 || :
    check_target_sums "top_shelf"

    # This runs if the modified file is not found.
    # Then we copy the AIBoard.qml file to our workdir.
    cp $TOP_SHELF_SOURCE "$WORKDIR/TopShelf.qml"

    # Finally we modify the file.
    sed -i '17 i return' "$WORKDIR/TopShelf.qml"
}

remove_top_shelf() {
    # First we check if the TopShelf.qml file exists on the USB. If it does not we create it.
    if [ $TOP_SHELF_ENABLED = true ]; then
        if [ ! -f "$WORKDIR/TopShelf.qml" ]; then
            echo "TopShelf override file did not exist. Creating one now."
            create_top_shelf_override
        else
            echo "TopShelf override file found at $WORKDIR/TopShelf.qml"
        fi
        # Then we mount --bind the TopShelf.qml override file. This is a non destructive action that can be reset with a reboot or umount.
        mount --bind "$WORKDIR/TopShelf.qml" "$AI_BOARD_SOURCE"
    else
        echo "TopShelf block disabled. Reverting changes"
        umount "$TOP_SHELF_SOURCE" > /dev/null 2>&1 || :
        rm -fr $WORKDIR/TopShelf.qml
    fi
}

create_app_interfaces_override() {
    umount "$APP_INTERFACES_SOURCE" > /dev/null 2>&1 || :
    # check_target_sums "app_interfaces"

    # This runs if the modified file is not found.
    # Then we copy the AIBoard.qml file to our workdir.
    cp $APP_INTERFACES_SOURCE "$WORKDIR/AppInterfaces.qml"

    # Finally we modify the file.
    sed -i '312 i console.log("HERE", item)' "$WORKDIR/AppInterfaces.qml"
}

debug_app_interfaces() {
    if [ 1 = 1 ]; then
        if [ ! -f "$WORKDIR/AppInterfaces.qml" ]; then
            echo "AppInterfaces override file did not exist. Creating one now."
            create_app_interfaces_override
        else
            echo "AppInterfaces override file found at $WORKDIR/AppInterfaces.qml"
        fi
        # Then we mount --bind the AppInterfaces.qml override file. This is a non destructive action that can be reset with a reboot or umount.
        mount --bind "$WORKDIR/AppInterfaces.qml" "$APP_INTERFACES_SOURCE"
    else
        echo "AppInterfaces block disabled. Reverting changes"
        umount "$APP_INTERFACES_SOURCE" > /dev/null 2>&1 || :
        rm -fr $WORKDIR/AppInterfaces.qml
    fi
}

init() {
    pkill -f com.webos.app.home
    # Make sure WAR_ENABLED is not set to false
    check_war_enabled
    # Check install
    check_install
    # This is the entrypoint for the script.
    check_workdir
    # Optional. This removes the AI Board (Top bar with 3 boxes. Includes ad, hero banner)
    remove_ai_board
    # Optional. This removes the trending section
    remove_recommended
    # Optional. This removes the whole top shelf container
    remove_top_shelf

    debug_app_interfaces

    # When we are done we kill webOS home. This forces it to restart and use our changes.
    pkill -f com.webos.app.home
}

init
